# Generated by Django 5.1.7 on 2025-12-07 17:36

import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authenticationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(default='patient', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('governorate', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('verification_token', models.CharField(default=secrets.token_urlsafe, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'مستخدم مؤقت',
                'verbose_name_plural': 'مستخدمين مؤقتين',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='accounts_pe_email_1e1edb_idx'), models.Index(fields=['verification_token'], name='accounts_pe_verific_5a64dd_idx'), models.Index(fields=['-created_at'], name='accounts_pe_created_c72a0c_idx')],
            },
        ),
    ]
