# Generated by Django 5.1.7 on 2025-12-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_message_options_remove_message_body_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
