# Generated by Django 5.1.7 on 2025-12-05 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'إنشاء حساب'), ('login', 'تسجيل الدخول'), ('login_failed', 'فشل تسجيل الدخول'), ('logout', 'تسجيل الخروج'), ('password_reset_request', 'طلب إعادة تعيين كلمة المرور'), ('password_reset_confirm', 'تأكيد إعادة تعيين كلمة المرور'), ('email_verification', 'تفعيل البريد الإلكتروني'), ('email_verification_resend', 'إعادة إرسال رابط التفعيل')], max_length=30, verbose_name='العملية')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم المستخدم')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, verbose_name='نجحت العملية')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل المصادقة',
                'verbose_name_plural': 'سجلات المصادقة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_au_created_f669a5_idx'), models.Index(fields=['user', '-created_at'], name='accounts_au_user_id_e8b400_idx'), models.Index(fields=['action', '-created_at'], name='accounts_au_action_a0d55a_idx'), models.Index(fields=['email', '-created_at'], name='accounts_au_email_ce5277_idx'), models.Index(fields=['ip_address', '-created_at'], name='accounts_au_ip_addr_ca7ed1_idx')],
            },
        ),
    ]
